### ISSUE TITLE
Enemy Movement

### ISSUE THREAD

**Issue by ryansouthern** [zbaker94/GameDesign_spring15_FinalProject#10]
this needs to be cleaned up.
it flips upside down when it turns (or when its stuck)
it also gets stuck on the player. (if you move the play on top of the enemy. )

**Comment by zbaker94** [comment]
Updated everything to use a new system, no more flipping etc. still gets stuck on cathedrals, but this may be due to the spawning algorithm.

**Comment by dblack20** [comment]
if this is closed why does it show open?
