### ISSUE TITLE
Destroy cathedrals animation 

### ISSUE THREAD

**Issue by ryansouthern** [zbaker94/GameDesign_spring15_FinalProject#2]
they need to explode (or crumble) when the player destroys it.

**Comment by wallace989** [comment]
I added an explosion class and attempted to delete the cathedral after the player collides with it

**Comment by wallace989** [comment]
there are also some images and sounds that go with the explosion

**Comment by ryansouthern** [comment]
closing.  this is the same as the explosion ticket.
