### ISSUE TITLE
Make the player shoot

### ISSUE THREAD

**Issue by ryansouthern** [zbaker94/GameDesign_spring15_FinalProject#3]
The player needs to be able to shoot ammo.

**Comment by ryansouthern** [comment]
dependent on https://github.com/zbaker94/GameDesign_spring15_FinalProject/issues/8

**Comment by zbaker94** [comment]
Player now shoots in direction it is facing, ammo decreases when shot and increases when picked up. still need to add ui for bullets remaining.

**Comment by ryansouthern** [comment]
closing and opening "add ui for bullets remaining"
