### ISSUE TITLE
8-Bit Art

### ISSUE THREAD

**Issue by ryansouthern** [zbaker94/GameDesign_spring15_FinalProject#5]
We need the background images and cathedral images for levels 2-4

**Comment by dblack20** [comment]
I got em.  turning all into .png format in simple graphics.  I can tart
them up later is desired.  Posting ten or so in few minutes

On Wed, Mar 25, 2015 at 4:20 PM, Ryan Southern notifications@github.com
wrote:

> We need the background images and cathedral images for levels 2-4
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zbaker94/GameDesign_spring15_FinalProject/issues/5.

## 

Dave Black
770-827-0166

**Comment by wallace989** [comment]
![francecathedral](https://cloud.githubusercontent.com/assets/11539681/7166011/2b89265a-e379-11e4-9452-79d07e614752.PNG)

Here is a Church I made if yall like it
