### ISSUE TITLE
Enemy shooting

### ISSUE THREAD

**Issue by ryansouthern** [zbaker94/GameDesign_spring15_FinalProject#6]
have the enemy shoot the player

**Comment by ryansouthern** [comment]
dependent on https://github.com/zbaker94/GameDesign_spring15_FinalProject/issues/8

**Comment by zbaker94** [comment]
Enemies now shoot in the direction of the player (still on 4 axes) using a fairly complex set of if else statements. this same algorithm is used for their changing movement when shot.
